"""IDs for datasets"""

# * US data (FRED API)
US_CPI = "CPIAUCNS"
US_CPI_SEASONAL_ADJ = "CPIAUCSL"
US_CPI_NONDURABLES = "CUUR0000SAN"
US_CPI_DURABLES = "CUUR0000SAD"
US_INF_EXPECTATIONS = "MICH"
US_NONDURABLES_CONSUMPTION = "PCEND"
US_DURABLES_CONSUMPTION = "PCEDG"
US_SAVINGS = "PMSAVE"
US_SAVINGS_RATE = "PSAVERT"

# * French data (INSEE API)
# TODO

# * French data (CAMME survey data)
# TODO
