"""IDs for datasets"""

# * US data (FRED API)
US_CPI = "CPIAUCNS"
US_CPI_SEASONAL_ADJ = "CPIAUCSL"
US_CPI_NONDURABLES = "CUUR0000SAN"
US_CPI_DURABLES = "CUUR0000SAD"
US_INF_EXPECTATIONS = "MICH"
US_NONDURABLES_CONSUMPTION = "PCEND"
US_DURABLES_CONSUMPTION = "PCEDG"
US_SAVINGS = "PMSAVE"
US_SAVINGS_RATE = "PSAVERT"

# * French data (FRED API)
FR_CPI = "FRACPIALLMINMEI"

# * French data (INSEE API)
FR_INF_EXPECTATIONS = "000857180"
FR_INF_PERCEPTIONS = "000857179"
FR_FOOD_CONSUMPTION = "011794482"
FR_GOODS_CONSUMPTION = "011794487"
FR_DURABLES_CONSUMPTION = "011794493"
